### ISSUE TITLE
Use environment variable TARGET in build.rs for platform detection.

### ISSUE THREAD

**Issue by slyshykO** [rep-nop/mac_address#10] opened 2019-08-27 02:01 UTC
Because macro cfg work improperly when cross-compile.

usage example:

```rust
use std::env;
fn main() {
    let target = match env::var("TARGET") {
        Err(e) => {eprintln!("{:?}", e); "NO TARGET".to_string()},
        Ok(val) => val,
    };
    if target.contains("windows") {
        println!("cargo:rustc-link-lib=iphlpapi");
   }
}
```

https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts

**Comment by rep-nop** [comment] 2019-09-21 19:41
Sorry for the delay! I'm not quite sure what the issue is here -- I wasn't able to reproduce this on my machine ```
repnop@snek /m/F/D/R/mac_address> cargo check --target x86_64-pc-windows-gnu
   Compiling winapi-x86_64-pc-windows-gnu v0.4.0
   Compiling winapi v0.3.7
   Compiling mac_address v1.0.1 (/mnt/F/Development/Rust/mac_address)
    Finished dev [unoptimized + debuginfo] target(s) in 4.71s
```
Is there some more context you can provide on what your issue is?

**Comment by rep-nop** [comment] 2019-09-21 19:48
Ah, after talking with someone else I understand your issue now. I'll push out a fix shortly, thanks for the bug report!

**Comment by rep-nop** [comment] 2019-09-21 19:52
Fixed with commit https://github.com/rep-nop/mac_address/commit/bafb0de2da898db1c18ecccac58c85c05335ac10, new version has been published to crates.io as `1.0.2`

**Closed by rep-nop** 2019-09-21 19:52 UTC
